# Generated by Django 5.0.3 on 2024-11-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('travel_entry_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=25)),
                ('planner_id', models.CharField(max_length=25)),
                ('user_id', models.CharField(max_length=25)),
                ('aiport_code', models.CharField(blank=True, max_length=25, null=True)),
                ('flight_no', models.CharField(blank=True, max_length=10, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_location', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_date', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_location', models.CharField(blank=True, max_length=100, null=True)),
                ('airline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=25, null=True)),
                ('dtentry', models.DateTimeField(auto_now=True)),
                ('iGuestId', models.CharField(blank=True, max_length=25, null=True)),
                ('cStatus', models.CharField(blank=True, max_length=25, null=True)),
                ('travel_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
